[package]
name = "tiktoken"
version = "0.1.0"
edition = "2021"
rust-version = "1.57.0"

[lib]
name = "tiktoken"

[dev-dependencies]
criterion = "0.4"

[dependencies]
fancy-regex = "0.11.0"
regex = "1.8.3"
rustc-hash = "1.1.0"
bstr = "1.5.0"
hex = "0.4.3"
sha2 = "0.10.6"
base64 = "0.21.0"
thiserror = "1.0.38"

[[bench]]
name = "bench"
harness = false